- alias: sensor_ldr_kamer_bas_turn_on_light
  initial_state: True
  trigger:
    - platform: numeric_state
      entity_id: sensor.lichtsterkte
      below: 200
      for:
        seconds: 30
  condition:
    condition: and
    conditions:
      - condition: time
        before: '22:00:00'
      - condition: state
        entity_id: switch.game_pc
        state: "on"
  action:
    - service: light.turn_on
      entity_id: light.ai_light_room_bas