- platform: buienradar
  name: Buienradar
  monitored_conditions:
    - symbol
    - humidity
    - temperature
    - temperature_1d
    - windspeed
    - pressure
    - irradiance
    - visibility
    - winddirection
    - rainchance_1d