automations:
  view: yes
  name: Automations
  icon: mdi:home-automation
  entities:
    - group.theme
    - group.room_bas_automations
    - group.zone_automations
    - group.notifications
    - group.notification_actions
    - group.scripts